const assert = require("assert");
const path = require("path");

const styles = require(path.join("..", "uxp", "panel-styles.js"));

function sliceBetween(startMarker, endMarker) {
  const start = styles.indexOf(startMarker);
  assert(start >= 0, `missing CSS start marker: ${startMarker}`);
  if (!endMarker) {
    return styles.slice(start);
  }
  const end = styles.indexOf(endMarker, start + startMarker.length);
  assert(end > start, `missing CSS end marker after ${startMarker}: ${endMarker}`);
  return styles.slice(start, end);
}

assert.strictEqual(typeof styles, "string", "panel styles module must export CSS text");
assert(styles.includes("cursor: default"), "panel must reset Photoshop tool cursors when the pointer enters the panel");
assert(styles.includes("cursor: pointer"), "panel controls must expose an explicit clickable cursor");
assert(styles.includes("cursor: text"), "numeric inputs must expose an explicit text-edit cursor");
assert(styles.includes("ok-record-group-title"), "panel must group the dense control surface with flat workflow headers");
assert(styles.includes("background: #000000"), "panel must use the black shell background");
assert(styles.includes("background: #1e1e1e"), "panel must use the dark panel surface");
assert(styles.includes("width: 100%"), "panel must fill the host panel width instead of using a fixed inner width");
assert(styles.includes("max-width: none"), "panel must not cap itself at a fixed width inside the host panel");
assert(styles.includes("height: 100vh"), "panel must fill the host panel height");
assert(!styles.includes("max-width: 500px"), "panel must not keep a fixed 500px inner shell");
assert(styles.includes("border: 0"), "panel shell must not add an inner fixed chrome frame");
assert(styles.includes("background: #171717"), "export notice must use the segmented dark surface");
assert(styles.includes("background: #242424"), "active states must use the selected segment surface");
assert(styles.includes("#9db7ff"), "active states must use the selected underline accent");
assert(styles.includes("rgba(235, 240, 248, 0.64)"), "group headers must use muted header text");
assert(styles.includes("border-radius: 10px"), "action controls must use the rounded chrome radius");
assert(!styles.includes("#fffaf1"), "panel must not use the retired warm prototype surface");
assert(!styles.includes("transform 160ms ease"), "buttons must not animate geometry because it destabilizes hover hit testing");
assert(!styles.includes(".ok-record-group-title::before"), "group headers must not use a pseudo-element triangle");
assert(!styles.includes(".ok-record-group-title::after"), "group headers must not use a pseudo-element separator");
assert(styles.includes("input.ok-record-number-editor-input {"), "numeric editor must style the transient edit input directly");
assert(styles.includes(".ok-record-number-input {"), "numeric fields must use a focused class selector instead of styling every input");
assert(!styles.includes("input {\n      box-sizing: border-box;\n      flex: 0 0 96px"), "text-field chrome must not apply to checkbox inputs");
assert(styles.includes(".ok-record-short-number"), "short numeric inputs must keep their own compact width rule");
assert(styles.includes("flex-basis: 56px"), "short numeric inputs must fit roughly 4-5 digits instead of six");
assert(styles.includes("width: 56px"), "short numeric inputs must use the compact 56px width");
assert(styles.includes(".ok-record-short-number {\n    flex-basis: 56px;\n    width: 56px;\n    text-align: right;"), "short numeric inputs must request right-aligned values");
assert(!styles.includes("flex: 1 0 144px"), "action buttons must not reintroduce wrap-first minimum widths");
assert(!styles.includes("min-width: 144px"), "action buttons must not reintroduce wrap-first minimum widths");
assert(styles.includes("button:active"), "panel buttons must expose an explicit pressed interaction state");
assert(styles.includes("overflow-y: auto"), "panel must scroll vertically instead of clipping controls");
assert(styles.includes("overflow-x: hidden"), "panel must avoid horizontal clipping scroll for the fixed control surface");
assert(styles.includes(".ok-record-panel::-webkit-scrollbar"), "panel must hide the visible scrollbar chrome");

const groupTitleCss = sliceBetween(".ok-record-group-title {", ".ok-record-group-title-text {");
const groupTitleTextCss = sliceBetween(".ok-record-group-title-text {", ".ok-record-group-title-rule {");
const exportGroupTitleCss = sliceBetween(".ok-record-export-group .ok-record-group-title {", ".ok-record-group-body {");
const panelCss = sliceBetween(".ok-record-panel {", ".ok-record-group {");
const panelScrollbarCss = sliceBetween(".ok-record-panel::-webkit-scrollbar {", ".ok-record-group {");
const groupCss = sliceBetween(".ok-record-group {", ".ok-record-group + .ok-record-group {");
const groupSiblingCss = sliceBetween(".ok-record-group + .ok-record-group {", ".ok-record-group-title {");
const groupBodyCss = sliceBetween(".ok-record-group-body {", ".ok-record-export-notice {");
const recordingGroupBodyCss = sliceBetween(".ok-record-recording-group .ok-record-group-body {", ".ok-record-recording-group .ok-record-field {");
const exportGroupBodyCss = sliceBetween(".ok-record-export-group .ok-record-group-body {", ".ok-record-export-notice {");
const recordingGroupFieldCss = sliceBetween(".ok-record-recording-group .ok-record-field {", ".ok-record-field-label {");
const exportNoticeCss = sliceBetween(".ok-record-export-notice {", ".ok-record-export-notice-visible {");
const exportNoticeBodyCss = sliceBetween(".ok-record-export-notice-body {", ".ok-record-field {");
const fieldCss = sliceBetween(".ok-record-field {", ".ok-record-field-label {");
const fieldLabelCss = sliceBetween(".ok-record-field-label {", ".ok-record-field-controls {");
const fieldControlsCss = sliceBetween(".ok-record-field-controls {", ".ok-record-number-input {");
const inputCss = sliceBetween(".ok-record-number-input {", "select {");
const selectCss = sliceBetween("select {", ".ok-record-number-input:hover");
const inputStateCss = sliceBetween(".ok-record-number-input:hover", ".ok-record-quality-controls {");
const qualityControlsCss = sliceBetween(".ok-record-quality-controls {", ".ok-record-quality-option {");
const timerControlCss = sliceBetween(".ok-record-timer-control-row {", ".ok-record-timer-status-button {");
const timerStatusButtonCss = sliceBetween(".ok-record-timer-status-button {", ".ok-record-button-row {");
const buttonLabelCss = sliceBetween(".ok-record-button-label {", "  button:hover,");
const buttonInteractionCss = sliceBetween("  button:hover,", "  button:focus,");
const buttonRowCss = sliceBetween(".ok-record-button-row {", ".ok-record-button-row > * {");
const buttonRowSpacingCss = sliceBetween(".ok-record-button-row > * {", ".ok-record-button-row button {");
const buttonRowButtonCss = sliceBetween(".ok-record-button-row button {", ".ok-record-button-row .ok-record-control-button {");
const primaryActionRowCss = sliceBetween(".ok-record-primary-action-row {", ".ok-record-recording-button-row-gap {");
const recordingButtonRowGapCss = sliceBetween(".ok-record-recording-button-row-gap {", ".ok-record-recording-input-row-gap {");
const recordingInputRowGapCss = sliceBetween(".ok-record-recording-input-row-gap {", ".ok-record-export-action-row-gap {");
const exportActionRowGapCss = sliceBetween(".ok-record-export-action-row-gap {", ".ok-record-export-button-row-gap {");
const exportButtonRowGapCss = sliceBetween(".ok-record-export-button-row-gap {", ".ok-record-export-input-row-gap {");
const exportInputRowGapCss = sliceBetween(".ok-record-export-input-row-gap {", ".ok-record-directory-row button {");
const directoryRowButtonCss = sliceBetween(".ok-record-directory-row button {", ".ok-record-compact-button {");
const recordingStatusButtonCss = sliceBetween(".ok-record-record-status-button,", ".ok-record-step-indicator {");
const exportStatusButtonCss = sliceBetween(".ok-record-export-status-button {", ".ok-record-record-status-button .ok-record-button-label,");
const recordingActiveStatusCss = sliceBetween(".ok-record-record-status-button.ok-record-state-active {", "  button:disabled,");

assert(!groupTitleCss.includes("font-size: " + "3" + "2px"), "group headers must not keep retired oversized title text");
assert(groupTitleCss.includes("font-size: 24px"), "group headers must use the requested 24px title text");
assert(groupTitleCss.includes("font-weight: 700"), "group headers are the only title-weight labels");
assert(!groupTitleCss.includes("font-size: 16px"), "group titles must not keep the retired 16px text size");
assert(groupTitleCss.includes("display: flex"), "group headers must use a stable flex row instead of a grid-only header");
assert(groupTitleCss.includes("justify-content: center"), "group headers must center title text between rules");
assert(groupTitleCss.includes("gap: 0"), "group headers must not rely on flex gap for UXP separator spacing");
assert(groupTitleCss.includes("margin: 0 0 16px"), "group header must explicitly control the 16px title-to-body distance");
assert(groupTitleTextCss.includes("margin: 0 24px"), "group header text must keep an explicit 24px margin from separator rules");
assert(exportGroupTitleCss.includes("margin-bottom: 0"), "export group title must sit directly above its first field");

assert(panelCss.includes("gap: 0"), "panel spacing must not rely on flex gap in Photoshop UXP");
assert(panelCss.includes(".ok-record-panel-section-gap"), "panel groups must use explicit spacer nodes for reliable spacing");
assert(panelCss.includes("flex: 0 0 20px"), "panel section spacer nodes must keep a reliable 20px vertical distance");
assert(panelCss.includes("height: 20px"), "panel section spacer nodes must have real height instead of a margin that Photoshop UXP may drop");
assert(panelCss.includes("height: 100vh"), "panel must fill the host panel height");
assert(panelCss.includes("overflow-y: auto"), "panel must own vertical scrolling when the host panel is shortened");
assert(panelCss.includes("scrollbar-width: none"), "panel must hide the visible scrollbar while preserving scrolling");
assert(panelScrollbarCss.includes("display: none"), "panel must hide Chromium/WebKit scrollbars in Photoshop UXP");
assert(!panelCss.includes("min-width: 500px"), "panel must not turn the manifest default width into a fixed CSS minimum");
assert(groupCss.includes("flex: 0 0 auto"), "groups must not shrink vertically and overlap when panel height is reduced");
assert(groupCss.includes("gap: 0"), "title-to-body spacing must not come from the group flex gap");
assert(groupSiblingCss.includes("margin-top: 0"), "group spacing must not stack an extra group margin on top of panel sibling spacing");
assert(groupBodyCss.includes("gap: 12px"), "group controls must keep a safe vertical distance");
assert(groupBodyCss.includes("flex: 0 0 auto"), "group bodies must preserve their content height for panel scrolling");
assert(recordingGroupBodyCss.includes("gap: 0"), "recording group must disable unreliable flex gap before using real spacer nodes");
assert(recordingGroupFieldCss.includes("min-height: 28px"), "recording input rows must use the right-side input height as the spacing box");
assert(exportGroupBodyCss.includes("gap: 0"), "export group must disable unreliable flex gap before using real spacer nodes");
assert(exportActionRowGapCss.includes("flex: 0 0 0"), "export action spacer must collapse to zero height");
assert(exportActionRowGapCss.includes("height: 0"), "export action spacer must remove the quality-to-button distance");
assert(exportButtonRowGapCss.includes("flex: 0 0 12px"), "export directory-to-video spacer must keep the requested 12px height");
assert(exportButtonRowGapCss.includes("height: 12px"), "export directory-to-video spacer must use real height instead of margin");
assert(exportInputRowGapCss.includes("flex: 0 0 8px"), "export input spacers must keep a real 8px height");
assert(exportInputRowGapCss.includes("height: 8px"), "export input spacers must use real height instead of margin");
assert(exportNoticeCss.includes("display: none"), "export notice must stay hidden until export success or failure");
assert(exportNoticeCss.includes("flex: 0 0 auto"), "export notice must not shrink vertically under short panel heights");
assert(exportNoticeCss.includes("margin: 0"), "hidden export notice must not leave stray spacing");
assert(styles.includes(".ok-record-export-notice-visible {\n    display: flex;\n    margin-top: 12px;"), "visible export notice must sit 12px below the export button");
assert(exportNoticeBodyCss.includes("font-size: 13px"), "export notice details must stay compact instead of using full control text size");

assert(fieldCss.includes("font-size: 16px"), "field labels must use the requested 16px ordinary text size");
assert(fieldCss.includes("line-height: 20px"), "field labels must keep a 20px line height for 16px ordinary text");
assert(fieldCss.includes("color: #cccccc"), "ordinary field text must use the requested #cccccc color");
assert(fieldCss.includes("gap: 0"), "fields must not rely on flex gap for label/control spacing in Photoshop UXP");
assert(fieldCss.includes("padding: 0"), "field row vertical spacing must come from group-body gap instead of row padding");
assert(fieldCss.includes("flex: 0 0 auto"), "field rows must not shrink vertically under short panel heights");
assert(fieldLabelCss.includes("font-weight: 400"), "field labels must not be independently bolded");
assert(fieldLabelCss.includes("color: #cccccc"), "field labels must use the requested #cccccc color");
assert(fieldLabelCss.includes("ok-record-field-label-gap"), "fields must use a real spacer node between labels and controls");
assert(fieldLabelCss.includes("text-align: left"), "field labels must stay on the left side of input rows");
assert(fieldLabelCss.includes("flex: 1 1 180px"), "field labels must reserve a stable left column before the right-side controls");
assert(fieldControlsCss.includes("gap: 0"), "field controls must not rely on flex gap for input/unit spacing in Photoshop UXP");
assert(fieldControlsCss.includes("ok-record-field-control-gap"), "field controls must use explicit spacer nodes between inputs and units");
assert(fieldControlsCss.includes("flex: 0 0 auto"), "field control clusters must keep stable height under short panel heights");
assert(qualityControlsCss.includes("flex: 0 0 auto"), "quality preset controls must not shrink vertically under short panel heights");
assert(qualityControlsCss.includes("gap: 0"), "quality controls must not rely on flex gap in Photoshop UXP");

assert(inputCss.includes("-webkit-appearance: none"), "numeric fields must suppress native field chrome");
assert(inputCss.includes("appearance: none"), "numeric fields must suppress native field chrome");
assert(inputCss.includes("display: flex"), "numeric fields must render as custom flex controls");
assert(inputCss.includes("justify-content: flex-end"), "numeric display values must align to the right edge");
assert(inputCss.includes("box-shadow: none"), "numeric fields must not carry a raised inner shadow");
assert(inputCss.includes("border: 1px solid #5a5a5a"), "inputs must use the original thin outline field style");
assert(inputCss.includes("border-radius: 6px"), "inputs must keep the original small outline radius");
assert(inputCss.includes("background: #1f1f1f"), "inputs must use the original dark line-box fill");
assert(inputCss.includes("color: #ffffff"), "inputs must keep clear white value text");
assert(inputCss.includes("text-align: right"), "numeric fields must request right-aligned values");
assert(inputCss.includes(".ok-record-number-input.ok-record-number-editing {\n    padding: 0;"), "numeric editing state must remove outer padding so the transient editor is not clipped");
assert(inputCss.includes("input.ok-record-number-editor-input"), "numeric field CSS must include the transient editor style");
assert(inputCss.includes("padding: 3px 8px"), "transient editor must own its vertical padding instead of inheriting a clipped content box");
assert(inputCss.includes("line-height: 20px"), "transient editor must use a taller line height to avoid clipped digits");
assert(inputCss.includes("font-variant-numeric: tabular-nums"), "transient editor must match the display numeric metrics");
assert(selectCss.includes("appearance: none"), "selects must suppress native dropdown appearance");
assert(selectCss.includes("height: 28px"), "selects must use the same stable height as line-box numeric fields");
assert(selectCss.includes("line-height: 18px"), "selects must align text inside the stable line box");
assert(selectCss.includes("box-shadow: none"), "selects must suppress native shadow or underline artifacts");
assert(selectCss.includes("border: 1px solid #5a5a5a"), "selects must visually match the original thin outline fields");
assert(selectCss.includes("background: #1f1f1f"), "selects must visually match the original dark line-box fill");
assert(inputStateCss.includes("border-color: #6a6a6a"), "input hover state must stay as a line-border change");
assert(inputStateCss.includes("border-color: #9db7ff"), "input focus state must stay as a line-border change");
assert(inputStateCss.includes("box-shadow: none"), "input focus must explicitly suppress native/glowing shadows");
assert(!inputStateCss.includes("0 0 0 2px"), "input focus must not use the retired glowing field treatment");

assert(timerControlCss.includes("justify-content: center"), "painting timer row must center the timer status button");
assert(timerControlCss.includes("gap: 0"), "painting timer controls must not depend on flex gap for spacing");
assert(timerControlCss.includes("margin-top: 0"), "painting timer button row must sit directly under the OK-Record settings title");
assert(!timerControlCss.includes("ok-record-painting-timeout-field"), "painting timer idle threshold must use the shared settings field layout");
assert(!timerControlCss.includes("margin-left"), "painting timer row must not keep retired spacing for a removed reset icon");
assert(timerControlCss.includes("flex: 0 0 auto"), "timer control row must not shrink vertically under short panel heights");
assert(timerStatusButtonCss.includes("min-width: 150px"), "painting timer status button must keep a stable centered width");
assert(timerStatusButtonCss.includes("height: 48px"), "painting timer status button must use the requested 48px height");
assert(timerStatusButtonCss.includes("font-size: 16px"), "painting timer status button text must use the requested 16px size");
assert(timerStatusButtonCss.includes("font-weight: 700"), "painting timer status button text must be bold");
assert(timerStatusButtonCss.includes("justify-content: center"), "painting timer status button content must be centered");
assert(timerStatusButtonCss.includes("text-align: center"), "painting timer status text must be centered");
assert(!timerStatusButtonCss.includes("ok-record-timer-status-prefix"), "painting timer status text must not keep the split-prefix layout");
assert(timerStatusButtonCss.includes("ok-record-timer-indicator-slot"), "painting timer indicator must use a fixed slot for vertical centering");
assert(timerStatusButtonCss.includes("height: 22px"), "painting timer indicator slot must match the timer label line height");
assert(timerStatusButtonCss.includes("width: 14px"), "painting timer indicator slot must match the requested 14px dot width");
assert(timerStatusButtonCss.includes("ok-record-timer-indicator"), "painting timer status button must render a circular status indicator");
assert(timerStatusButtonCss.includes("margin-right: 10px"), "painting timer indicator must keep a fixed gap before the whole text");
assert(timerStatusButtonCss.includes("height: 14px"), "painting timer indicator must use the requested 14px dot size");
assert(timerStatusButtonCss.includes("ok-record-timer-indicator-active"), "painting timer status button must have an active indicator state");
assert(timerStatusButtonCss.includes("background: #ff5a5a"), "painting timer active indicator must be red");
assert(timerStatusButtonCss.includes("ok-record-timer-indicator-waiting"), "painting timer status button must have a waiting indicator state");
assert(timerStatusButtonCss.includes("background: #17e57e"), "painting timer waiting indicator must use the requested green color");
assert(timerStatusButtonCss.includes("ok-record-timer-indicator-idle"), "painting timer status button must have an idle indicator state");
assert(timerStatusButtonCss.includes("background: #f2c94c"), "painting timer idle indicator must be yellow");
assert(timerStatusButtonCss.includes("ok-record-timer-text"), "painting timer whole text must render after the indicator");
assert(timerStatusButtonCss.includes("transform: translateY(-1px)"), "painting timer text must keep the requested 1px upward optical offset");
assert(timerStatusButtonCss.includes("ok-record-timer-clock-active"), "painting timer status button must color active timing separately");
assert(timerStatusButtonCss.includes("ok-record-timer-clock-ended"), "painting timer status button must color ended timing separately");
assert(timerStatusButtonCss.includes("color: #ff6666"), "painting timer ended status text must use the requested red color");
assert(timerStatusButtonCss.includes("cursor: pointer"), "painting timer status button must own the start and pause click target");

assert(recordingStatusButtonCss.includes("font-size: 16px"), "recording status button text must match the painting timer status size");
assert(recordingStatusButtonCss.includes("font-weight: 700"), "recording status button text must be bold like the painting timer status");
assert(recordingStatusButtonCss.includes("ok-record-export-status-button"), "export video button must share the status-button layout");
assert(exportStatusButtonCss.includes("height: 40px"), "export video button height must use the requested 40px baseline");
assert(exportStatusButtonCss.includes("min-height: 40px"), "export video button must not inherit the 48px primary-action height");
assert(recordingActiveStatusCss.includes(".ok-record-record-status-button.ok-record-state-active"), "recording status button must own a non-generic active style");
assert(recordingActiveStatusCss.includes("rgba(157, 183, 255, 0.86)"), "recording active status must keep the blue outline instead of turning gray");
assert(recordingActiveStatusCss.includes("rgba(255, 90, 90, 0.88)"), "recording active status must use the red recording accent without a gray disabled treatment");
assert(recordingStatusButtonCss.includes("ok-record-record-indicator-slot"), "recording status button must render a fixed indicator slot");
assert(recordingStatusButtonCss.includes("width: 14px"), "recording status indicator must use the same 14px dot size as the painting timer");
assert(recordingStatusButtonCss.includes("height: 14px"), "recording status indicator must use the same 14px dot size as the painting timer");
assert(recordingStatusButtonCss.includes("background: transparent"), "recording status indicator must not have a gray default dot");
assert(recordingStatusButtonCss.includes("ok-record-record-indicator-active"), "recording status button must have an active indicator state");
assert(recordingStatusButtonCss.includes("background: #ff5a5a"), "recording active indicator must be red");
assert(recordingStatusButtonCss.includes("ok-record-record-indicator-paused"), "recording status button must have a paused indicator state");
assert(recordingStatusButtonCss.includes("background: #f2c94c"), "recording paused indicator must be yellow");
assert(recordingStatusButtonCss.includes("ok-record-record-text"), "recording status text must render after the indicator");
assert(recordingStatusButtonCss.includes("transform: translateY(-1px)"), "recording status text must share the painting timer optical offset");
assert(recordingStatusButtonCss.includes("ok-record-export-indicator-slot"), "export status button must render a fixed indicator slot");
assert(!styles.includes("ok-record-export-indicator-slot-hidden"), "export status button must not carry a hidden idle indicator slot");
assert(!styles.includes("ok-record-export-indicator-idle"), "export status button must not define a neutral idle dot");
assert(!recordingStatusButtonCss.includes("rgba(235, 240, 248, 0.34)"), "export idle indicator must not use a neutral status dot color");
assert(recordingStatusButtonCss.includes("ok-record-export-indicator-exporting"), "export status button must have an exporting indicator state");
assert(recordingStatusButtonCss.includes("background: #f2c94c"), "export exporting indicator must be yellow");
assert(recordingStatusButtonCss.includes("ok-record-export-indicator-success"), "export status button must have a success indicator state");
assert(recordingStatusButtonCss.includes("background: #17e57e"), "export success indicator must be green");
assert(recordingStatusButtonCss.includes("ok-record-export-indicator-failure"), "export status button must have a failure indicator state");
assert(!styles.includes("ok-record-export-indicator-hidden"), "export status button must not carry a hidden idle indicator dot");
assert(recordingStatusButtonCss.includes("ok-record-export-text"), "export status text must render after the indicator");
assert(styles.includes(".ok-record-export-status-button.ok-record-export-state-visible:disabled"), "export progress status must remain readable while the disabled button blocks repeat clicks");
assert(styles.includes(".ok-record-export-status-button.ok-record-export-state-visible.ok-record-control-disabled"), "export progress status must remain readable on the shared control-button surface");
assert(styles.includes("ok-record-step-indicator-sampling"), "manual sampling button must expose a sampling indicator state");
assert(styles.includes("ok-record-step-indicator-success"), "manual sampling button must expose a completed sampling indicator state");

assert(buttonLabelCss.includes("font-size: 14px"), "button text must stay ordinary action text, not title text");
assert(buttonLabelCss.includes("font-weight: 400"), "button text must not be independently bolded like a title");
assert(buttonLabelCss.includes("white-space: nowrap"), "button labels must stay on one line");
assert(buttonLabelCss.includes("text-overflow: ellipsis"), "button labels must truncate instead of wrapping");
assert(!buttonInteractionCss.includes("transform:"), "button hover and pressed states must not move the hit target");
assert(buttonRowCss.includes("flex-wrap: nowrap"), "button rows must stay on one line");
assert(buttonRowCss.includes("flex: 0 0 auto"), "button rows must not shrink vertically under short panel heights");
assert(buttonRowCss.includes("gap: 0"), "button rows must not depend on flex gap for horizontal spacing");
assert(buttonRowCss.includes("margin: 0"), "button row vertical spacing must come from group-body gap instead of row margins");
assert(primaryActionRowCss.includes("justify-content: center"), "primary action rows must keep the three main buttons centered");
assert(primaryActionRowCss.includes("flex: 0 1 190px"), "recording and manual sampling buttons must match the painting timer width contract");
assert(primaryActionRowCss.includes("width: 190px"), "primary action buttons must share the painting timer fixed width");
assert(primaryActionRowCss.includes("min-width: 150px"), "primary action buttons must share the painting timer minimum width");
assert(primaryActionRowCss.includes("max-width: 240px"), "primary action buttons must share the painting timer maximum width");
assert(buttonRowSpacingCss.includes("margin: 0"), "button row children must reset native margins before explicit spacing");
assert(buttonRowSpacingCss.includes("margin-left: 8px"), "button row children must use explicit 8px spacing between adjacent controls");
assert(buttonRowButtonCss.includes("flex: 1 1 0"), "action buttons must share one row");
assert(buttonRowButtonCss.includes("min-width: 0"), "action buttons must not force row wrapping");
assert(recordingButtonRowGapCss.includes("flex: 0 0 12px"), "recording button rows must use real 12px spacer nodes instead of flex gap");
assert(recordingButtonRowGapCss.includes("height: 12px"), "recording button row spacer nodes must have real height");
assert(recordingInputRowGapCss.includes("flex: 0 0 8px"), "recording controls and input rows must use real 8px spacer nodes instead of flex gap");
assert(recordingInputRowGapCss.includes("height: 8px"), "recording input row spacer nodes must have real 8px height");
assert(directoryRowButtonCss.includes("height: 32px"), "recording directory buttons must use the requested 32px height");
assert(directoryRowButtonCss.includes("min-height: 32px"), "recording directory buttons must not grow taller than the requested 32px baseline");
assert(directoryRowButtonCss.includes("max-height: 32px"), "recording directory buttons must not exceed the requested 32px height");
assert(directoryRowButtonCss.includes("padding: 0 10px"), "recording directory buttons must not use native vertical padding that expands height");

console.log("panel-styles tests passed");
